# Generated by Django 2.1.5 on 2019-01-24 18:44

import Event.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('registration_from', models.DateTimeField(blank=True, null=True)),
                ('registration_to', models.DateTimeField(blank=True, null=True)),
                ('event_from', models.DateTimeField(blank=True, null=True)),
                ('event_to', models.DateTimeField(blank=True, null=True)),
                ('participant_limit', models.IntegerField(default=0)),
                ('participant_count', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('rules', models.TextField()),
                ('prize', models.TextField()),
                ('brochure', models.FileField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('web_priority', models.IntegerField(default=0)),
                ('app_priority', models.IntegerField(default=0)),
                ('registration_closed', models.BooleanField(default=False)),
                ('team_event', models.BooleanField(default=False)),
                ('organisers', models.ManyToManyField(related_name='organising_events', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(related_name='volunteering_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventCatalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=Event.models.get_event_photo_path)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_of', to='Event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=50, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_events', to='Event.Event')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader_of', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belong_to_team', to='Event.Team'),
        ),
    ]
