# Generated by Django 2.1.5 on 2019-01-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuth', '0002_auto_20190122_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
